server:
  port: ${gateway.port}
spring:
  application:
    name: cloud-gateway

  cloud:
    nacos:
      # nacos服务注册中心配置
      discovery:
        server-addr: ${nacos.config.server-addr}
        namespace: ${nacos.config.namespace}
    gateway:
      # 开启动态路由
      discovery:
        locator:
          enabled: true
      # 路由信息
      routes:
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: admin-server
          uri: lb://admin-server
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2